name: Unikorn Merge
on:
  push:
    branches:
    - main
    tags-ignore:
    - '*'
env:
  GO_VERSION: 1.21.1
jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Install Helm
      uses: azure/setup-helm@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Install Helm
      uses: azure/setup-helm@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: helm/chart-releaser-action@v1.4.1
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CR_SKIP_EXISTING: 'true'
    - name: Touch
      run: make touch
    - name: Unit Test
      run: make test-unit
    - name: Run Codecov
      uses: codecov/codecov-action@v3
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
