name: Release
on:
  push:
    branches-ignore:
    - '*'
    tags:
    - '*'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
    - name: Install Helm
      uses: azure/setup-helm@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: helm/chart-releaser-action@v1.4.1
      env:
        CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CR_SKIP_EXISTING: 'true'
